# Generates Version.h from the latest git tag (run by the build before compiling).
#   v1.2.3            -> "1.2.3"                  / 1,2,3,0
#   2 commits later   -> "1.2.3-2-g6f2787f"       / 1,2,3,2
#   uncommitted edits -> "1.2.3-2-g6f2787f-dirty"
#   no git / no repo  -> "dev"                    / 0,0,0,0
param([Parameter(Mandatory = $true)][string]$OutFile)

$desc = ''
try {
    $desc = & git -C $PSScriptRoot describe --tags --always --dirty --match 'v[0-9]*' 2>$null
    if ($LASTEXITCODE -ne 0) { $desc = '' }
} catch {
    $desc = ''
}
$desc = "$desc".Trim()
if (-not $desc) { $desc = 'dev' }

# From here on, any failure (e.g. Version.h not writable) must fail the build
$ErrorActionPreference = 'Stop'

$version = $desc -replace '^v', ''
$major = 0; $minor = 0; $patch = 0; $build = 0
if ($desc -match '^v(\d+)\.(\d+)\.(\d+)(?:-(\d+)-g[0-9a-f]+)?') {
    $major = [int]$Matches[1]
    $minor = [int]$Matches[2]
    $patch = [int]$Matches[3]
    if ($Matches[4]) { $build = [Math]::Min([int]$Matches[4], 65535) }
}

$content = @"
// Generated by GenVersion.ps1 - do not edit, do not commit.
#pragma once
#define APP_VERSION_STR    "$version"
#define APP_VERSION_WSTR   L"$version"
#define APP_VERSION_COMMAS $major,$minor,$patch,$build

"@ -replace "`r`n", "`n"

# Only rewrite when the content changes, so unchanged builds stay incremental
$current = if (Test-Path $OutFile) { [IO.File]::ReadAllText($OutFile) } else { $null }
if ($current -ne $content) {
    [IO.File]::WriteAllText($OutFile, $content, (New-Object Text.ASCIIEncoding))
    Write-Host "Version.h: $version"
}
